"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 The TUnits Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _UnitEnum:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _UnitEnumEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_UnitEnum.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DECIBEL: _UnitEnum.ValueType  # 1
    """Power unit (dB)."""
    DECIBEL_MILLIWATTS: _UnitEnum.ValueType  # 2
    """Decibel-milliwatts (dBm)."""
    RADIANS: _UnitEnum.ValueType  # 3
    """Radians (rad)."""
    HERTZ: _UnitEnum.ValueType  # 4
    """Frequency unit (Hz)."""
    VOLT: _UnitEnum.ValueType  # 5
    """Electric potential Unit (V)."""
    SECOND: _UnitEnum.ValueType  # 6
    """Time unit (s)."""

class UnitEnum(_UnitEnum, metaclass=_UnitEnumEnumTypeWrapper):
    """Units supported for serialization."""

DECIBEL: UnitEnum.ValueType  # 1
"""Power unit (dB)."""
DECIBEL_MILLIWATTS: UnitEnum.ValueType  # 2
"""Decibel-milliwatts (dBm)."""
RADIANS: UnitEnum.ValueType  # 3
"""Radians (rad)."""
HERTZ: UnitEnum.ValueType  # 4
"""Frequency unit (Hz)."""
VOLT: UnitEnum.ValueType  # 5
"""Electric potential Unit (V)."""
SECOND: UnitEnum.ValueType  # 6
"""Time unit (s)."""
Global___UnitEnum: _TypeAlias = UnitEnum  # noqa: Y015

class _Scale:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ScaleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Scale.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    YOTTA: _Scale.ValueType  # 24
    """Enum value should be the associated exponent.
    10^24
    """
    ZETTA: _Scale.ValueType  # 21
    """10^21"""
    EXA: _Scale.ValueType  # 18
    """10^18"""
    PETA: _Scale.ValueType  # 15
    """10^15"""
    TERA: _Scale.ValueType  # 12
    """10^12"""
    GIGA: _Scale.ValueType  # 9
    """10^9"""
    MEGA: _Scale.ValueType  # 6
    """10^6"""
    KILO: _Scale.ValueType  # 3
    """10^3"""
    HECTO: _Scale.ValueType  # 2
    """10^2"""
    DECAD: _Scale.ValueType  # 1
    """10^1"""
    UNITY: _Scale.ValueType  # 0
    """1"""
    DECI: _Scale.ValueType  # -1
    """10^-1"""
    CENTI: _Scale.ValueType  # -2
    """10^-2"""
    MILLI: _Scale.ValueType  # -3
    """10^-3"""
    MICRO: _Scale.ValueType  # -6
    """10^-6"""
    NANO: _Scale.ValueType  # -9
    """10^-9"""
    PICO: _Scale.ValueType  # -12
    """10^-12"""
    FEMTO: _Scale.ValueType  # -15
    """10^-15"""
    ATTO: _Scale.ValueType  # -18
    """10^-18"""
    ZEPTO: _Scale.ValueType  # -21
    """10^-21"""
    YOCTO: _Scale.ValueType  # -24
    """10^-24"""

class Scale(_Scale, metaclass=_ScaleEnumTypeWrapper): ...

YOTTA: Scale.ValueType  # 24
"""Enum value should be the associated exponent.
10^24
"""
ZETTA: Scale.ValueType  # 21
"""10^21"""
EXA: Scale.ValueType  # 18
"""10^18"""
PETA: Scale.ValueType  # 15
"""10^15"""
TERA: Scale.ValueType  # 12
"""10^12"""
GIGA: Scale.ValueType  # 9
"""10^9"""
MEGA: Scale.ValueType  # 6
"""10^6"""
KILO: Scale.ValueType  # 3
"""10^3"""
HECTO: Scale.ValueType  # 2
"""10^2"""
DECAD: Scale.ValueType  # 1
"""10^1"""
UNITY: Scale.ValueType  # 0
"""1"""
DECI: Scale.ValueType  # -1
"""10^-1"""
CENTI: Scale.ValueType  # -2
"""10^-2"""
MILLI: Scale.ValueType  # -3
"""10^-3"""
MICRO: Scale.ValueType  # -6
"""10^-6"""
NANO: Scale.ValueType  # -9
"""10^-9"""
PICO: Scale.ValueType  # -12
"""10^-12"""
FEMTO: Scale.ValueType  # -15
"""10^-15"""
ATTO: Scale.ValueType  # -18
"""10^-18"""
ZEPTO: Scale.ValueType  # -21
"""10^-21"""
YOCTO: Scale.ValueType  # -24
"""10^-24"""
Global___Scale: _TypeAlias = Scale  # noqa: Y015

@_typing.final
class Fraction(_message.Message):
    """The exponent of a unit e.g.
    m^3 gives numerator=3, denominator=1.
    sqrt(Hz) gives numerator=1, denominator=2.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NUMERATOR_FIELD_NUMBER: _builtins.int
    DENOMINATOR_FIELD_NUMBER: _builtins.int
    numerator: _builtins.int
    denominator: _builtins.int
    def __init__(
        self,
        *,
        numerator: _builtins.int | None = ...,
        denominator: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["denominator", b"denominator", "numerator", b"numerator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["denominator", b"denominator", "numerator", b"numerator"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Fraction: _TypeAlias = Fraction  # noqa: Y015

@_typing.final
class Unit(_message.Message):
    """Unit message has a base unit, a scale and an exponent, e.g. 1/sqrt(ns)
    becomes unit=SECOND, scale=NANO, exponent.numerator=-1,
    exponent.denominator=2
    """

    DESCRIPTOR: _descriptor.Descriptor

    UNIT_FIELD_NUMBER: _builtins.int
    SCALE_FIELD_NUMBER: _builtins.int
    EXPONENT_FIELD_NUMBER: _builtins.int
    unit: Global___UnitEnum.ValueType
    scale: Global___Scale.ValueType
    @_builtins.property
    def exponent(self) -> Global___Fraction: ...
    def __init__(
        self,
        *,
        unit: Global___UnitEnum.ValueType | None = ...,
        scale: Global___Scale.ValueType | None = ...,
        exponent: Global___Fraction | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["exponent", b"exponent", "scale", b"scale", "unit", b"unit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["exponent", b"exponent", "scale", b"scale", "unit", b"unit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Unit: _TypeAlias = Unit  # noqa: Y015

@_typing.final
class Complex(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REAL_FIELD_NUMBER: _builtins.int
    IMAGINARY_FIELD_NUMBER: _builtins.int
    real: _builtins.float
    imaginary: _builtins.float
    def __init__(
        self,
        *,
        real: _builtins.float | None = ...,
        imaginary: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["imaginary", b"imaginary", "real", b"real"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["imaginary", b"imaginary", "real", b"real"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Complex: _TypeAlias = Complex  # noqa: Y015

@_typing.final
class Value(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    UNITS_FIELD_NUMBER: _builtins.int
    REAL_VALUE_FIELD_NUMBER: _builtins.int
    COMPLEX_VALUE_FIELD_NUMBER: _builtins.int
    real_value: _builtins.float
    @_builtins.property
    def units(self) -> _containers.RepeatedCompositeFieldContainer[Global___Unit]:
        """Units are repeated to represent combinations of units (e.g. V*s and mV/us).
        Units are combined through multiplication.
        """

    @_builtins.property
    def complex_value(self) -> Global___Complex: ...
    def __init__(
        self,
        *,
        units: _abc.Iterable[Global___Unit] | None = ...,
        real_value: _builtins.float | None = ...,
        complex_value: Global___Complex | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["complex_value", b"complex_value", "real_value", b"real_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["complex_value", b"complex_value", "real_value", b"real_value", "units", b"units", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["real_value", "complex_value"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___Value: _TypeAlias = Value  # noqa: Y015

@_typing.final
class DoubleArray(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        values: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DoubleArray: _TypeAlias = DoubleArray  # noqa: Y015

@_typing.final
class ComplexArray(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedCompositeFieldContainer[Global___Complex]: ...
    def __init__(
        self,
        *,
        values: _abc.Iterable[Global___Complex] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ComplexArray: _TypeAlias = ComplexArray  # noqa: Y015

@_typing.final
class ValueArray(_message.Message):
    """Represents an array with associated units (a collection of values that share
    the same units).
    """

    DESCRIPTOR: _descriptor.Descriptor

    UNITS_FIELD_NUMBER: _builtins.int
    REALS_FIELD_NUMBER: _builtins.int
    COMPLEXES_FIELD_NUMBER: _builtins.int
    SHAPE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def units(self) -> _containers.RepeatedCompositeFieldContainer[Global___Unit]:
        """Units are repeated to represent combinations of units (e.g. V*s and mV/us).
        Units are combined through multiplication.
        """

    @_builtins.property
    def reals(self) -> Global___DoubleArray:
        """The flattened array."""

    @_builtins.property
    def complexes(self) -> Global___ComplexArray: ...
    @_builtins.property
    def shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """The shape of the array."""

    def __init__(
        self,
        *,
        units: _abc.Iterable[Global___Unit] | None = ...,
        reals: Global___DoubleArray | None = ...,
        complexes: Global___ComplexArray | None = ...,
        shape: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["complexes", b"complexes", "reals", b"reals", "values", b"values"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["complexes", b"complexes", "reals", b"reals", "shape", b"shape", "units", b"units", "values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_values: _TypeAlias = _typing.Literal["reals", "complexes"]  # noqa: Y015
    _WhichOneofArgType_values: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_values) -> _WhichOneofReturnType_values | None: ...

Global___ValueArray: _TypeAlias = ValueArray  # noqa: Y015
